# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-19 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('description', models.CharField(max_length=512)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Country')),
            ],
        ),
    ]
